[versions]
kotlin_stdlib = "1.6.10"

com_fasterxml_jackson_databind = "2.12.5"
org_apache_xmlbeans = "5.0.1"
org_slf4j = "1.7.28"
org_slf4j_simple = "1.7.28"

org_junit_jupiter_api = "5.7.2"
org_junit_jupiter_engine = "5.7.2"
